apiVersion: v1
kind: PersistentVolume
metadata:
  name: automagic-media-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /automagic_media
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automagic-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
