apiVersion: v1
kind: PersistentVolume
metadata:
  name: automagic-static-pv
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /automagic_static

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: automagic-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: manual
