apiVersion: v1
kind: Service
metadata:
  name: automagic-app
  labels:
    name: automagic-app
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: automagic-app
